version: 2.1

orbs:
  win: circleci/windows@2.4.0


jobs:

  test_windows:
    executor:
      name: win/default
      size: "medium"
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            pip.exe install -r requirements.txt
      - run:
          name: "Run Tests"
          command: pytest test.py

workflows:
  version: 2
  test_windows:
    jobs:
      - test_windows
